// This file is automatically generated by Laravel Mix.
// Please do not make changes in this file directly.
import '../css/app.css';
import Alpine from 'alpinejs';

window.Alpine = Alpine;
Alpine.start();
